/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebLlmRouteImport } from './routes/web-llm'
import { Route as IndexRouteImport } from './routes/index'

const WebLlmRoute = WebLlmRouteImport.update({
  id: '/web-llm',
  path: '/web-llm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/web-llm': typeof WebLlmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/web-llm': typeof WebLlmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/web-llm': typeof WebLlmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/web-llm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/web-llm'
  id: '__root__' | '/' | '/web-llm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WebLlmRoute: typeof WebLlmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-llm': {
      id: '/web-llm'
      path: '/web-llm'
      fullPath: '/web-llm'
      preLoaderRoute: typeof WebLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WebLlmRoute: WebLlmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
